POST https://learning-node-nekd.onrender.com/videos
Content-Type: application/json 
# TEM QUE DIZER O TIPO A SER ENVIADO
Accept-Language: pt

{
    "title": "Video node",
    "description": "Esse é o video 01",
    "duration": 150
}


###
# TRES # SEPARA AS REQUISIÇOES

# USA ASSIM PRA PEGAR TODOS
GET https://learning-node-nekd.onrender.com/videos

###

# USA ASSIM PRA BUSCAR VIDEOS ESPECIFICOS
GET https://learning-node-nekd.onrender.com/videos?search=node

###

PUT https://learning-node-nekd.onrender.com/videos/dc491519-f6f1-4cef-8d9e-10f3b3362dc6
Content-Type: application/json 
# TEM QUE DIZER O TIPO A SER ENVIADO
Accept-Language: pt

{
    "title": "Video 02",
    "description": "Esse é o video 2",
    "duration": 180
}

###

DELETE https://learning-node-nekd.onrender.com/videos/dc491519-f6f1-4cef-8d9e-10f3b3362dc6